### ISSUE TITLE
MoveWindowToDesktopNumber

### ISSUE THREAD

**Issue by darkzbaron** [Ciantic/VirtualDesktopAccessor#8] opened 2016-07-24 10:01 UTC
Is this working with the new fix. Can't seem to have any luck with that. Thanks for the great piece of work and swift update.

**Comment by Ciantic** [comment] 2016-07-24 16:26
Unfortunately no. This is not an issue I can fix, because there is no _known_ way to move a window without injecting to the window's process a own DLL, or otherwise running code in it's process memory.

If one goes this route e.g. https://github.com/cspotcode/virtual-desktop-grid-switcher and more specifically here: https://github.com/cspotcode/virtual-desktop-grid-switcher/tree/master/VDMHelper-master it makes the program to work like a virus, and I don't want this DLL to act like one.

I close cause this is duplicate of #2 and it can be discussed there. I think this need is valid and maybe addressed in future if there is a good way to do it.

**Closed by Ciantic** 2016-07-24 16:26 UTC

**Comment by darkzbaron** [comment] 2016-07-27 10:59
Hi,thanks for the Feedback and detailed explanations. I really appreciate.

**Comment by Ciantic** [comment] 2016-08-05 19:51
I'm happily announcing that it's now possible! I've closed the main issue, the example is on the README
